### ISSUE TITLE
BJ_LED detects LED strip but gives error when adding the integration.

### ISSUE THREAD

**Issue by jalorenzo** [8none1/bj_led#2] opened 2024-03-16 18:11 UTC
Hello,

I am running HA in a Rpi 4. When I try to install the BJ_LED integration in HA (Core 2024.3.0, Supervisor 2024.03.0), it correctly detects the device's MAC of the LED strip.  However, when I click on submit, it shows a "unknown error" message. A look at the logs shows the messages below:

```
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 502, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bj_led/config_flow.py", line 91, in async_step_user
    self.name = self.context["title_placeholders"]["name"]
                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'title_placeholders'
```

I cannot find anything related in the Internet. Any ideas of what could be the cause?

Thanks in advance

**Comment by 8none1** [comment] 2024-03-16 18:36
I'm not sure what might cause this, but I have seen this error in other integrations.  I'll see if I can recreate it.

**Comment by 8none1** [comment] 2024-03-17 12:24
Ok, I've got a recreator I think:

- Have multiple devices
- Configure the first device though the prompt at the top of the integration screen
- Note that there is no prompt for the second device
- In the integration try and configure the second device which does have a correct name and mac address
- get the error

Now to work out why.  I don't really understand all the HA plumbing so I'm just gonna add bunch of prints and see if I can muddle through :D

**Comment by 8none1** [comment] 2024-03-17 13:54
Made some changes, and now the reproducer is:
 - Add two devices from the main integration screen
 - Everything works
 - Remove one device
 - Re-add that device
 - BOOM

**Comment by 8none1** [comment] 2024-03-17 14:04
Here's the result of the extra logging.  

### When added from main integration screen
```
2024-03-17 13:53:04.874 DEBUG (MainThread) [custom_components.bj_led.config_flow] step_user user_input: {'mac': 'ff:ff:10:af:0f:13'}
2024-03-17 13:53:04.874 DEBUG (MainThread) [custom_components.bj_led.config_flow] step_user context: {'source': 'bluetooth', 'unique_id': 'FF:FF:10:AF:0F:13', 'title_placeholders': {'name': 'BJ_LED (0F13)'}, 'confirm_only': True}
2024-03-17 13:53:04.874 DEBUG (MainThread) [custom_components.bj_led.bjled] New instance. Address passed is: ff:ff:10:af:0f:13
2024-03-17 13:53:04.874 DEBUG (MainThread) [custom_components.bj_led.bjled] Formatted mac as: FF:FF:10:AF:0F:13
2024-03-17 13:53:04.874 DEBUG (MainThread) [custom_components.bj_led.bjled] Asked for device from address and got: FF:FF:10:AF:0F:13: BJ_LED.
2024-03-17 13:53:04.875 DEBUG (MainThread) [custom_components.bj_led.bjled] Model information for device BJ_LED : ModelNo 0. MAC: FF:FF:10:AF:0F:13
```

### When added from the config screen
```
2024-03-17 13:53:41.898 DEBUG (MainThread) [custom_components.bj_led.config_flow] Discovered supported devices: BJ_LED (83CF) - ff:ff:10:ae:83:cf
2024-03-17 13:53:43.778 DEBUG (MainThread) [custom_components.bj_led.config_flow] step_user user_input: {'mac': 'ff:ff:10:ae:83:cf'}
2024-03-17 13:53:43.779 DEBUG (MainThread) [custom_components.bj_led.config_flow] step_user context: {'source': 'user', 'show_advanced_options': True}
2024-03-17 13:53:43.779 ERROR (MainThread) [aiohttp.server] Error handling request
```


The difference is that when added from the config screen the additional context information is missing.

**Comment by 8none1** [comment] 2024-03-17 20:16
Good news!  This should be fixed.  If you installed via HACS it should prompt you to upgrade.  Please test at your convienience and report back here.

https://github.com/8none1/bj_led/commit/6d383d77091570288a42c81ab7cd3f0ce87ca59d#diff-cbae5cb682c988044045d4771189aecb1098ed59f72c7b241a97d59bba9447d3R92

The bad news is that despite the investigation work I still don't really understand if this is the correct way to fix it or not.  But, meh, it works for me.

**Comment by jalorenzo** [comment] 2024-03-18 11:12
Hi, sorry that I couldn't test it until today. It works great, thanks very much for the quick reply!

**Comment by 8none1** [comment] 2024-03-18 11:13
Excellent, glad to hear it!

Thanks for reporting the issue.

Closing as fixed!

**Closed as completed by 8none1** 2024-03-18 11:13 UTC
